/** @type {import('tailwindcss').Config} */
export default {
  content: ['./app/**/*.{vue,ts}'],
  theme: {
    extend: {
      colors: {
        canvas: '#1A1F21',
        panel: '#2B3336',
        'layer-01': '#22282A',
        subtle: '#3A4245',
        'subtle-hover': '#4C5659',
        strong: '#5C6669',
        primary: '#F9F9F9',
        secondary: '#C9C7C4',
        helper: '#8C8782',
        'on-color': '#ffffff',
        accent: '#ED7B3D',
        'accent-text-on': '#ffffff',
        'tag-red-bg': '#B81C23',
        'tag-red-border': '#FA6B6B',
        'tag-red-text': '#FFD9D6',
        'tag-gold-bg': '#3A3220',
        'tag-gold-border': '#F5D45A',
        'tag-gold-text': '#FCEFC2',
        'tag-green-bg': '#198038',
        'tag-green-border': '#5CB87A',
        'tag-green-text': '#D3F2DE',
        'tag-teal-bg': '#0E6C60',
        'tag-teal-border': '#5BB5A6',
        'tag-teal-text': '#CBEDE6',
        'tag-gray-bg': '#2B3336',
        'tag-gray-border': '#4C5659',
        'tag-gray-text': '#F9F9F9',
      },
      fontFamily: {
         heading: ['Aleo', 'Fustat', 'Georgia', 'Times New Roman', 'serif'],
        body: ['IBM Plex Sans', 'IBM Plex Sans Arabic', '-apple-system', 'BlinkMacSystemFont', 'sans-serif'],
      },
      fontSize: {
        'display-lg': '32px',
        'display-md': '25px',
        'display-sm': '21px',
        'body-lg': '16px',
        'body-md': '15px',
        body: '14px',
        caption: '13px',
        label: '12px',
        eyebrow: '10px',
      },
      letterSpacing: {
        tight: '0.16px',
        label: '0.32px',
      },
      borderRadius: {
        'tag-lg': '16px',
        'tag-sm': '9px',
      },
    },
  },
  plugins: [],
}
