/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  '/': {
    /** Home */
    get: operations['home__get']
  }
  '/api/analyze/': {
    /**
     * Submit an APK for analysis
     * @description Upload an APK file, computes its SHA-256 hash, and queues it for analysis. Return the SHA-256 hash of the APK file
     */
    post: operations['analyze_apk_api_analyze__post']
  }
  '/api/reports/': {
    /**
     * List all APK analyses
     * @description Return a list of all APK analysis reports that have been submitted and analyzed
     */
    get: operations['get_reports_api_reports__get']
  }
  '/api/report/{id}/': {
    /**
     * Get the full analysis report
     * @description Return the complete, aggregated analysis report (fingerprints, threat intelligence, app information, code analysis, behavior analysis, and network analysis)
     */
    get: operations['get_report_api_report__id___get']
  }
  '/api/report/{id}/verdict/': {
    /**
     * Get the sample's final verdict
     * @description Return the final verdict(malicious or not, severity, reason, response needed
     */
    get: operations['get_verdict_api_report__id__verdict__get']
  }
  '/api/report/{id}/fingerprints/': {
    /**
     * Get fingerprints data
     * @description Return all the fingerprints data (checksums, identifiers, fuzzy hashes)
     */
    get: operations['get_fingerprints_api_report__id__fingerprints__get']
  }
  '/api/report/{id}/fingerprints/checksums/': {
    /**
     * Get file checksums
     * @description Return file checksums (e.g. MD5, SHA256) computed
     */
    get: operations['get_checksums_api_report__id__fingerprints_checksums__get']
  }
  '/api/report/{id}/fingerprints/identifiers/': {
    /**
     * Get APK identifiers
     * @description Return packer/obfuscator/compiler identifiers
     */
    get: operations['get_identifiers_api_report__id__fingerprints_identifiers__get']
  }
  '/api/report/{id}/fingerprints/fuzzy-hashes/': {
    /**
     * Get fuzzy hashes
     * @description Return fuzzy hash values (e.g. ssdeep) used for similarity comparisons
     */
    get: operations['get_fuzzy_hashes_api_report__id__fingerprints_fuzzy_hashes__get']
  }
  '/api/report/{id}/threat-intelligence/': {
    /**
     * Get all threat intelligence data
     * @description Return all the threat intelligence data (sample timeline, YARA matches, antivirus detections, third-party lookups)
     */
    get: operations['get_threat_intelligence_api_report__id__threat_intelligence__get']
  }
  '/api/report/{id}/threat-intelligence/timeline/': {
    /**
     * Get sample timeline
     * @description Return key dates for the sample (file creation, certficate validaity, first/last submission)
     */
    get: operations['get_sample_timeline_api_report__id__threat_intelligence_timeline__get']
  }
  '/api/report/{id}/threat-intelligence/yara/': {
    /**
     * Get YARA rule matches
     * @description Return the YARA rule match results
     */
    get: operations['get_yara_analysis_api_report__id__threat_intelligence_yara__get']
  }
  '/api/report/{id}/threat-intelligence/popular-av-detections/': {
    /**
     * Get popular antivirus detections
     * @description Return the popular antivirus engine detections
     */
    get: operations['get_antivirus_detections_api_report__id__threat_intelligence_popular_av_detections__get']
  }
  '/api/report/{id}/threat-intelligence/third-party-apps/': {
    /**
     * Get 3rd-party lookup results
     * @description Return lookup results for 3rd-party threat intelligence sources (e.g. VirusTotal, MalwareBazaar)
     */
    get: operations['get_third_party_apps_api_report__id__threat_intelligence_third_party_apps__get']
  }
  '/api/report/{id}/app/': {
    /**
     * Get all app information
     * @description Return the full app information (details, certificates, manifests, activities, receivers, services)
     */
    get: operations['get_app_analysis_api_report__id__app__get']
  }
  '/api/report/{id}/app/details/': {
    /**
     * Get app details
     * @description Return basic app metadata (package name, version, size, etc.
     */
    get: operations['get_app_details_api_report__id__app_details__get']
  }
  '/api/report/{id}/app/certificate/': {
    /**
     * Get signing certificate details
     * @description Return the APK's signing certificate details (issuer, subject, validity, etc.)
     */
    get: operations['get_app_certificate_api_report__id__app_certificate__get']
  }
  '/api/report/{id}/app/manifests/': {
    /**
     * Get app manifests
     * @description Return a list of manifests declared in the app's manifest files (AndroidManifest.xml, etc.)
     */
    get: operations['get_app_manifests_api_report__id__app_manifests__get']
  }
  '/api/report/{id}/app/activities/': {
    /**
     * Get app activities
     * @description Return a list of activities declared in the app's manifest files (AndroidManifest.xml, etc. )
     */
    get: operations['get_app_activities_api_report__id__app_activities__get']
  }
  '/api/report/{id}/app/receivers/': {
    /**
     * Get app receivers
     * @description Return a list of receivers declared in the app's manifest files (AndroidManifest.xml, etc.)
     */
    get: operations['get_app_receivers_api_report__id__app_receivers__get']
  }
  '/api/report/{id}/app/services/': {
    /**
     * Get app services
     * @description Return a list of services declared in the app's manifest files (AndroidManifest.xml, etc.)
     */
    get: operations['get_app_services_api_report__id__app_services__get']
  }
  '/api/report/{id}/code/': {
    /**
     * Get all code analysis results
     * @description Return the full code analysis results (NIAP compliance, vulnerabilities)
     */
    get: operations['get_code_analysis_api_report__id__code__get']
  }
  '/api/report/{id}/code/niap/': {
    /**
     * Get NIAP analysis
     * @description Return the NIAP (National Information Assurance Program) compliance analysis results
     */
    get: operations['get_niap_analysis_api_report__id__code_niap__get']
  }
  '/api/report/{id}/code/vulnerabilities/': {
    /**
     * Get code vulnerabilities
     * @description Return a list of vulnerabilities detected via static analysis of the code
     */
    get: operations['get_code_vulnerabilities_api_report__id__code_vulnerabilities__get']
  }
  '/api/report/{id}/behavior/': {
    /**
     * Get all behavior analysis results
     * @description Return the full behavior analysis results (threats, permissions, detailed permissions)
     */
    get: operations['get_behavior_analysis_api_report__id__behavior__get']
  }
  '/api/report/{id}/behavior/threats/': {
    /**
     * Get behavioral threats
     * @description Return a list of threats (crimes) detected
     */
    get: operations['get_threats_analysis_api_report__id__behavior_threats__get']
  }
  '/api/report/{id}/behavior/permissions/': {
    /**
     * Get permissions analysis
     * @description Return a list of permissions requested by the APK
     */
    get: operations['get_permission_analysis_api_report__id__behavior_permissions__get']
  }
  '/api/report/{id}/behavior/detailed-permissions/': {
    /**
     * Get detailed permission analysis
     * @description Return a list of detailed permissions requested by the APK
     */
    get: operations['get_detailed_permissions_api_report__id__behavior_detailed_permissions__get']
  }
  '/api/report/{id}/control-flow/': {
    /**
     * Get control-flow graph data
     * @description Return the control-flow graph visualization of the behavior of the APK
     */
    get: operations['get_control_flow_api_report__id__control_flow__get']
  }
  '/api/report/{id}/network/': {
    /**
     * Get all network analysis
     * @description Return the network analysis results (domains and URLs)
     */
    get: operations['get_network_analysis_api_report__id__network__get']
  }
  '/api/report/{id}/network/domains/': {
    /**
     * Get network domains
     * @description Return a list of network domains accessed
     */
    get: operations['get_domain_analysis_api_report__id__network_domains__get']
  }
  '/api/report/{id}/network/urls/': {
    /**
     * Get network URLs
     * @description Return a list of network URLs accessed
     */
    get: operations['get_url_analysis_api_report__id__network_urls__get']
  }
}

export type webhooks = Record<string, never>

export interface components {
  schemas: {
    /**
     * APKDetailsResponse
     * @example {
     *   "app_name": "Google",
     *   "frosting": {
     *     "is_frosted": "N/A",
     *     "v2_signature_blocks": []
     *   },
     *   "package": "com.google.android",
     *   "sdk": "21 - None",
     *   "signature": "",
     *   "uaid": "58ef88f27b2b2c48519f804a4ff445e387cee78b",
     *   "version_code": 400000039,
     *   "version_name": "4.2.0"
     * }
     */
    APKDetailsResponse: {
      /**
       * Package
       * @description Package name of the APK
       */
      package?: string | null
      /**
       * App Name
       * @description Application name of the APK
       */
      app_name?: string | null
      /**
       * Version Name
       * @description Version name of the APK
       */
      version_name?: string | null
      /**
       * Version Code
       * @description Version code of the APK
       */
      version_code?: number | null
      /**
       * Sdk
       * @description Software Development Kit (SDK) used for the APK development
       */
      sdk?: string | null
      /**
       * Uaid
       * @description Unique Application Identifier (UAID) of the APK
       */
      uaid?: string | null
      /**
       * Signature
       * @description APK signature
       */
      signature?: string | null
      /** @description Frosting information of the APK */
      frosting?: components['schemas']['FrostingResponse'] | null
    }
    /**
     * APKDetailsSectionResponse
     * @example {
     *   "apk_details": {
     *     "computed_with": [
     *       "mobsf",
     *       "apk_info"
     *     ],
     *     "data": {
     *       "app_name": "Google",
     *       "frosting": {
     *         "is_frosted": "N/A",
     *         "v2_signature_blocks": []
     *       },
     *       "package": "com.google.android",
     *       "sdk": "21 - None",
     *       "signature": "",
     *       "uaid": "58ef88f27b2b2c48519f804a4ff445e387cee78b",
     *       "version_code": 400000039,
     *       "version_name": "4.2.0"
     *     }
     *   }
     * }
     */
    APKDetailsSectionResponse: {
      apk_details?: components['schemas']['Envelope_APKDetailsResponse_'] | null
    }
    /**
     * APKiDFiles
     * @example {
     *   "filename": "classes.dex",
     *   "matches": {
     *     "anti_debug": [
     *       "Debug.isDebuggerConnected() check"
     *     ],
     *     "anti_vm": [
     *       "Build.HARDWARE check"
     *     ],
     *     "compiler": [
     *       "r8"
     *     ],
     *     "manipulator": [
     *       "Resource Confusion"
     *     ],
     *     "obfuscator": [
     *       "Alipay"
     *     ],
     *     "protector": [
     *       "MSA SDK"
     *     ]
     *   }
     * }
     */
    APKiDFiles: {
      /**
       * Filename
       * @description Filename of the analyzed file
       */
      filename?: string | null
      /** @description Matches found in the analyzed file */
      matches?: components['schemas']['APKiDMatches'] | null
    }
    /**
     * APKiDMatches
     * @example {
     *   "anti_debug": [
     *     "Debug.isDebuggerConnected() check"
     *   ],
     *   "anti_vm": [
     *     "Build.HARDWARE check"
     *   ],
     *   "compiler": [
     *     "r8"
     *   ],
     *   "manipulator": [
     *     "Resource Confusion"
     *   ],
     *   "obfuscator": [
     *     "Alipay"
     *   ],
     *   "protector": [
     *     "MSA SDK"
     *   ]
     * }
     */
    APKiDMatches: {
      /**
       * Manipulator
       * @description List of indicators of alteration techniques found by analysis
       */
      manipulator?: string[] | null
      /**
       * Anti Debug
       * @description List of indicators of anti-debugging techniques found by analysis
       */
      anti_debug?: string[] | null
      /**
       * Anti Vm
       * @description List of indicators of anti-vm techniques found by analysis
       */
      anti_vm?: string[] | null
      /**
       * Compiler
       * @description List of suspecious compilers found
       */
      compiler?: string[] | null
      /**
       * Obfuscator
       * @description List of obfuscators found
       */
      obfuscator?: string[] | null
      /**
       * Protector
       * @description List of protectors found
       */
      protector?: string[] | null
    }
    /**
     * APKiDResponse
     * @example {
     *   "apkid_version": "3.6.6",
     *   "files": [
     *     {
     *       "filename": "classes.dex",
     *       "matches": {
     *         "anti_debug": [
     *           "Debug.isDebuggerConnected() check"
     *         ],
     *         "anti_vm": [
     *           "Build.HARDWARE check"
     *         ],
     *         "compiler": [
     *           "r8"
     *         ],
     *         "manipulator": [
     *           "Resource Confusion"
     *         ],
     *         "obfuscator": [
     *           "Alipay"
     *         ],
     *         "protector": [
     *           "MSA SDK"
     *         ]
     *       }
     *     }
     *   ],
     *   "rules_sha256": "e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855"
     * }
     */
    APKiDResponse: {
      /**
       * Apkid Version
       * @description APKiD verion
       */
      apkid_version?: string | null
      /** Files */
      files?: components['schemas']['APKiDFiles'][] | null
      /**
       * Rules Sha256
       * @description SHA256 hash of the YARA rules used by APKiD
       */
      rules_sha256?: string | null
    }
    /**
     * AVDetectionsResponse
     * @example [
     *   {
     *     "Avast": 12
     *   }
     * ]
     */
    AVDetectionsResponse:
      | {
          [key: string]: number
        }[]
      | {
          [key: string]: unknown
        }
      | null
    /**
     * AVDetectionsSectionResponse
     * @example {
     *   "popular_av_detections": {
     *     "computed_with": [
     *       "virustotal"
     *     ],
     *     "data": [
     *       {
     *         "Avast": 12
     *       }
     *     ]
     *   }
     * }
     */
    AVDetectionsSectionResponse: {
      popular_av_detections?: components['schemas']['Envelope_AVDetectionsResponse_'] | null
    }
    /**
     * ActivitiesResponse
     * @example {
     *   "all_activities": [
     *     "com.google.android",
     *     "com.chrome.android"
     *   ],
     *   "main_activity": "com.google.android"
     * }
     */
    ActivitiesResponse: {
      /**
       * Main Activity
       * @description Main activity used by the APK
       */
      main_activity?: string | null
      /**
       * All Activities
       * @description List of all activities used by the APK
       */
      all_activities?: string[] | null
    }
    /**
     * ActivitiesSectionResponse
     * @example {
     *   "activities": {
     *     "computed_with": [
     *       "mobsf"
     *     ],
     *     "data": {
     *       "all_activities": [
     *         "com.google.android",
     *         "com.chrome.android"
     *       ],
     *       "main_activity": "com.google.android"
     *     }
     *   }
     * }
     */
    ActivitiesSectionResponse: {
      activities?: components['schemas']['Envelope_ActivitiesResponse_'] | null
    }
    /**
     * AnalyzeResponse
     * @example {
     *   "id": "39ac2d9fe73cb2b4d16ae34bb27dce263c338f1c4e443213302bc3493e9de7eb",
     *   "status": "success"
     * }
     */
    AnalyzeResponse: {
      /** Status */
      status?: string | null
      /**
       * Id
       * @description SHA-256 hash of the submitted APK, used as the analysis report ID
       */
      id?: string | null
    }
    /**
     * ApiUsageFinding
     * @example {
     *   "files": {
     *     "jakhar/aseem/diva/MainActivity.java": "40,45,50"
     *   },
     *   "metadata": {
     *     "description": "Local File I/O Operations",
     *     "severity": "info"
     *   }
     * }
     */
    ApiUsageFinding: {
      /**
       * Files
       * @description Map of source file path to matching line number(s), comma-separated
       */
      files?: {
        [key: string]: string
      } | null
      metadata?: components['schemas']['ApiUsageMetadata'] | null
    }
    /**
     * ApiUsageMetadata
     * @example {
     *   "description": "Local File I/O Operations",
     *   "severity": "info"
     * }
     */
    ApiUsageMetadata: {
      /**
       * Description
       * @description Description of the API usage category
       */
      description?: string | null
      /**
       * Severity
       * @description Severity of the usage
       */
      severity?: string | null
    }
    /**
     * AppAnalysisResponse
     * @example {
     *   "acitivities": {
     *     "computed_with": [
     *       "mobsf"
     *     ],
     *     "data": {
     *       "all_activities": [
     *         "com.google.android",
     *         "com.chrome.android"
     *       ],
     *       "main_activity": "com.google.android"
     *     }
     *   },
     *   "apk_details": {
     *     "computed_with": [
     *       "mobsf",
     *       "apk_info"
     *     ],
     *     "data": {
     *       "app_name": "Google",
     *       "frosting": {
     *         "is_frosted": "N/A",
     *         "v2_signature_blocks": []
     *       },
     *       "package": "com.google.android",
     *       "sdk": "21 - None",
     *       "signature": "",
     *       "uaid": "58ef88f27b2b2c48519f804a4ff445e387cee78b",
     *       "version_code": 400000039,
     *       "version_name": "4.2.0"
     *     }
     *   },
     *   "certificate_details": {
     *     "computed_with": [
     *       "apk_info"
     *     ],
     *     "data": {
     *       "issuer": "Common Name: XX：XX, Organizational Unit: XXXX, Organization: XXXX, Locality: XX, State/Province: XX, Country: XXX",
     *       "md5": "9ddde935852443ac9ecc5e794f9917f0",
     *       "not_after": "3021-11-25T09:05:22+00:00",
     *       "not_before": "2023-07-25T09:05:22+00:00",
     *       "sha1": "a6ee6410327ed17751a3e4e7b7a03337d5c00611",
     *       "sha256": "b751f0afed43e56cab08e886d8b65a7a4da654d568e5313cfd056ec6a5b1e028"
     *     }
     *   },
     *   "manifest_analysis": {
     *     "computed_with": [
     *       "mobsf"
     *     ],
     *     "data": [
     *       {
     *         "component": [
     *           "5.0-5.0.2",
     *           "21"
     *         ],
     *         "description": "This application can be installed on an older version of android that has multiple unfixed vulnerabilities",
     *         "name": "vulnerable_os_version",
     *         "rule": "vulnerable_os_version",
     *         "severity": "high",
     *         "title": "App can be installed on a vulnerable unpatched Android version 5.0-5.0.2, [minSdk=21"
     *       }
     *     ]
     *   },
     *   "receivers": {
     *     "computed_with": [
     *       "mobsf"
     *     ],
     *     "data": [
     *       "com.google.android.commonlib.service.EnqueueService",
     *       "com.google.platform.oaidkit.OAIDLoadService"
     *     ]
     *   },
     *   "services": {
     *     "computed_with": [
     *       "mobsf"
     *     ],
     *     "data": [
     *       "com.google.android.share.douyin.StayInDouyinReceiver",
     *       "com.google.myssdk.share.callback.MysShareCallbackReceiver"
     *     ]
     *   }
     * }
     */
    AppAnalysisResponse: {
      apk_details?: components['schemas']['Envelope_APKDetailsResponse_'] | null
      certificate_details?: components['schemas']['Envelope_CertificateResponse_'] | null
      manifest_analysis?:
        components['schemas']['Envelope_Union_list_ManifestResponse___dict__'] | null
      acitivities?: components['schemas']['Envelope_ActivitiesResponse_'] | null
      receivers?: components['schemas']['Envelope_ReceiversResponse_'] | null
      services?: components['schemas']['Envelope_ServicesResponse_'] | null
    }
    /**
     * BehaviorAnalysisResponse
     * @example {
     *   "detailed_permissions": {
     *     "computed_with": [
     *       "mobsf"
     *     ],
     *     "data": {
     *       "api_local_file_io": {
     *         "files": {
     *           "jakhar/aseem/diva/MainActivity.java": "40,45,50"
     *         },
     *         "metadata": {
     *           "description": "Local File I/O Operations",
     *           "severity": "info"
     *         }
     *       }
     *     }
     *   },
     *   "permissions": {
     *     "computed_with": [
     *       "mobsf"
     *     ],
     *     "data": {
     *       "android.permission.SYSTEM_ALERT_WINDOW": {
     *         "description": "Allows an application to show system-alert windows. Malicious applications can take over the entire screen of the phone.",
     *         "info": "display system-level alerts",
     *         "status": "dangerous"
     *       }
     *     }
     *   },
     *   "threats": {
     *     "computed_with": [
     *       "quark_engine"
     *     ],
     *     "data": [
     *       {
     *         "confidence": "80%",
     *         "crime": "Read Sensitive Data"
     *       }
     *     ]
     *   }
     * }
     */
    BehaviorAnalysisResponse: {
      threats?: components['schemas']['Envelope_list_ThreatResponse__'] | null
      permissions?: components['schemas']['Envelope_PermissionsResponse_'] | null
      detailed_permissions?: components['schemas']['Envelope_DetailedPermissionsResponse_'] | null
    }
    /** Body_analyze_apk_api_analyze__post */
    Body_analyze_apk_api_analyze__post: {
      /**
       * File
       * @description APK file to analyze
       */
      file: string
    }
    /**
     * CertificateResponse
     * @example {
     *   "issuer": "Common Name: XX：XX, Organizational Unit: XXXX, Organization: XXXX, Locality: XX, State/Province: XX, Country: XXX",
     *   "md5": "9ddde935852443ac9ecc5e794f9917f0",
     *   "not_after": "3021-11-25T09:05:22+00:00",
     *   "not_before": "2023-07-25T09:05:22+00:00",
     *   "sha1": "a6ee6410327ed17751a3e4e7b7a03337d5c00611",
     *   "sha256": "b751f0afed43e56cab08e886d8b65a7a4da654d568e5313cfd056ec6a5b1e028"
     * }
     */
    CertificateResponse: {
      /**
       * Md5
       * @description MD5 hash of the certificate
       */
      md5?: string | null
      /**
       * Sha1
       * @description SHA1 hash of the certificate
       */
      sha1?: string | null
      /**
       * Sha256
       * @description SHA256 hash of the certificate
       */
      sha256?: string | null
      /**
       * Issuer
       * @description Issuer of the certificate
       */
      issuer?: string | null
      /**
       * Not Before
       * @description Creation date of the certificate
       */
      not_before?: string | null
      /**
       * Not After
       * @description Expiration date of the certificate
       */
      not_after?: string | null
    }
    /**
     * CertificateSectionResponse
     * @example {
     *   "certificate_details": {
     *     "computed_with": [
     *       "apk_info"
     *     ],
     *     "data": {
     *       "issuer": "Common Name: XX：XX, Organizational Unit: XXXX, Organization: XXXX, Locality: XX, State/Province: XX, Country: XXX",
     *       "md5": "9ddde935852443ac9ecc5e794f9917f0",
     *       "not_after": "3021-11-25T09:05:22+00:00",
     *       "not_before": "2023-07-25T09:05:22+00:00",
     *       "sha1": "a6ee6410327ed17751a3e4e7b7a03337d5c00611",
     *       "sha256": "b751f0afed43e56cab08e886d8b65a7a4da654d568e5313cfd056ec6a5b1e028"
     *     }
     *   }
     * }
     */
    CertificateSectionResponse: {
      certificate_details?: components['schemas']['Envelope_CertificateResponse_'] | null
    }
    /**
     * ChecksumResponse
     * @example {
     *   "md5": "f5936822b4567731e11bd3b03ad2305b",
     *   "sha1": "c705b93bce7efeedb5036d7416a056a7a01e6bea",
     *   "sha256": "39ac2d9fe73cb2b4d16ae34bb27dce263c338f1c4e443213302bc3493e9de7eb",
     *   "size": "55.67MB"
     * }
     */
    ChecksumResponse: {
      /**
       * Size
       * @description Size of the sample
       */
      size?: string | null
      /**
       * Md5
       * @description MD5 hash of the sample
       */
      md5?: string | null
      /**
       * Sha1
       * @description SHA1 hash of the sample
       */
      sha1?: string | null
      /**
       * Sha256
       * @description SHA256 hash of the sample
       */
      sha256?: string | null
    }
    /**
     * ChecksumSectionResponse
     * @example {
     *   "checksums": {
     *     "computed_with": [
     *       "mobsf"
     *     ],
     *     "data": {
     *       "md5": "f5936822b4567731e11bd3b03ad2305b",
     *       "sha1": "c705b93bce7efeedb5036d7416a056a7a01e6bea",
     *       "sha256": "39ac2d9fe73cb2b4d16ae34bb27dce263c338f1c4e443213302bc3493e9de7eb",
     *       "size": "55.67MB"
     *     }
     *   }
     * }
     */
    ChecksumSectionResponse: {
      checksums?: components['schemas']['Envelope_ChecksumResponse_'] | null
    }
    /**
     * CodeAnalysisResponse
     * @example {
     *   "code_vulnerabilties": {
     *     "computed_with": [
     *       "mobsf"
     *     ],
     *     "data": {
     *       "android_logging": {
     *         "files": {
     *           "jakhar/aseem/diva/LogActivity.java": "24"
     *         },
     *         "metadata": {
     *           "cvss": 7.5,
     *           "cwe": "CWE-532: Insertion of Sensitive Information into Log File",
     *           "description": "The App logs information. Sensitive information should never be logged.",
     *           "masvs": "MSTG-STORAGE-3",
     *           "owasp-mobile": "M2: Insecure Data Storage",
     *           "ref": "https://github.com/MobSF/owasp-mstg/blob/master/Document/0x05d-Testing-Data-Storage.md#logs",
     *           "severity": "warning"
     *         }
     *       }
     *     }
     *   },
     *   "niap_analysis": {
     *     "computed_with": [
     *       "mobsf"
     *     ],
     *     "data": {}
     *   }
     * }
     */
    CodeAnalysisResponse: {
      niap_analysis?: components['schemas']['Envelope_NiapAnalysisResponse_'] | null
      code_vulnerabilties?: components['schemas']['Envelope_CodeVulnerabilitiesResponse_'] | null
    }
    /**
     * CodeVulnerabilitiesResponse
     * @example {
     *   "android_logging": {
     *     "files": {
     *       "jakhar/aseem/diva/LogActivity.java": "24"
     *     },
     *     "metadata": {
     *       "cvss": 7.5,
     *       "cwe": "CWE-532: Insertion of Sensitive Information into Log File",
     *       "description": "The App logs information. Sensitive information should never be logged.",
     *       "masvs": "MSTG-STORAGE-3",
     *       "owasp-mobile": "M2: Insecure Data Storage",
     *       "ref": "https://github.com/MobSF/owasp-mstg/blob/master/Document/0x05d-Testing-Data-Storage.md#logs",
     *       "severity": "warning"
     *     }
     *   }
     * }
     */
    CodeVulnerabilitiesResponse: {
      [key: string]: components['schemas']['CodeVulnerabilityFinding']
    } | null
    /**
     * CodeVulnerabilitiesSectionResponse
     * @example {
     *   "code_vulnerabilities": {
     *     "computed_with": [
     *       "mobsf"
     *     ],
     *     "data": {
     *       "android_logging": {
     *         "files": {
     *           "jakhar/aseem/diva/LogActivity.java": "24"
     *         },
     *         "metadata": {
     *           "cvss": 7.5,
     *           "cwe": "CWE-532: Insertion of Sensitive Information into Log File",
     *           "description": "The App logs information. Sensitive information should never be logged.",
     *           "masvs": "MSTG-STORAGE-3",
     *           "owasp-mobile": "M2: Insecure Data Storage",
     *           "ref": "https://github.com/MobSF/owasp-mstg/blob/master/Document/0x05d-Testing-Data-Storage.md#logs",
     *           "severity": "warning"
     *         }
     *       }
     *     }
     *   }
     * }
     */
    CodeVulnerabilitiesSectionResponse: {
      code_vulnerabilities?: components['schemas']['Envelope_CodeVulnerabilitiesResponse_'] | null
    }
    /**
     * CodeVulnerabilityFinding
     * @example {
     *   "files": {
     *     "jakhar/aseem/diva/LogActivity.java": "24"
     *   },
     *   "metadata": {
     *     "cvss": 7.5,
     *     "cwe": "CWE-532: Insertion of Sensitive Information into Log File",
     *     "description": "The App logs information. Sensitive information should never be logged.",
     *     "masvs": "MSTG-STORAGE-3",
     *     "owasp-mobile": "M2: Insecure Data Storage",
     *     "ref": "https://github.com/MobSF/owasp-mstg/blob/master/Document/0x05d-Testing-Data-Storage.md#logs",
     *     "severity": "warning"
     *   }
     * }
     */
    CodeVulnerabilityFinding: {
      /**
       * Files
       * @description Map of source file path to matching line number(s), comma-separated
       */
      files?: {
        [key: string]: string
      } | null
      metadata?: components['schemas']['CodeVulnerabilityMetadata'] | null
    }
    /**
     * CodeVulnerabilityMetadata
     * @example {
     *   "cvss": 7.5,
     *   "cwe": "CWE-532: Insertion of Sensitive Information into Log File",
     *   "description": "The App logs information. Sensitive information should never be logged.",
     *   "masvs": "MSTG-STORAGE-3",
     *   "owasp-mobile": "M2: Insecure Data Storage",
     *   "ref": "https://github.com/MobSF/owasp-mstg/blob/master/Document/0x05d-Testing-Data-Storage.md#logs",
     *   "severity": "warning"
     * }
     */
    CodeVulnerabilityMetadata: {
      /**
       * Cvss
       * @description CVSS score of the finding
       */
      cvss?: number | null
      /**
       * Cwe
       * @description CWE identifier and title
       */
      cwe?: string | null
      /**
       * Owasp-Mobile
       * @description OWASP Mobile Top 10 category
       */
      'owasp-mobile'?: string | null
      /**
       * Masvs
       * @description MASVS control ID
       */
      masvs?: string | null
      /**
       * Ref
       * @description Reference link for the finding
       */
      ref?: string | null
      /**
       * Description
       * @description Description of the code finding
       */
      description?: string | null
      /**
       * Severity
       * @description Severity of the finding
       */
      severity?: string | null
    }
    /**
     * DetailedPermissionsResponse
     * @example {
     *   "api_local_file_io": {
     *     "files": {
     *       "jakhar/aseem/diva/MainActivity.java": "40,45,50"
     *     },
     *     "metadata": {
     *       "description": "Local File I/O Operations",
     *       "severity": "info"
     *     }
     *   }
     * }
     */
    DetailedPermissionsResponse: {
      [key: string]: components['schemas']['ApiUsageFinding']
    } | null
    /**
     * DetailedPermissionsSectionResponse
     * @example {
     *   "detailed_permissions": {
     *     "computed_with": [
     *       "mobsf"
     *     ],
     *     "data": {
     *       "api_local_file_io": {
     *         "files": {
     *           "jakhar/aseem/diva/MainActivity.java": "40,45,50"
     *         },
     *         "metadata": {
     *           "description": "Local File I/O Operations",
     *           "severity": "info"
     *         }
     *       }
     *     }
     *   }
     * }
     */
    DetailedPermissionsSectionResponse: {
      detailed_permissions?: components['schemas']['Envelope_DetailedPermissionsResponse_'] | null
    }
    /**
     * DomainInfoResponse
     * @example {
     *   "bad": "no",
     *   "geolocation": {
     *     "city": "San Francisco",
     *     "country_long": "United States of America",
     *     "country_short": "US",
     *     "ip": "172.67.72.183",
     *     "latitude": "37.775700",
     *     "longitude": "-122.395203",
     *     "region": "California"
     *   },
     *   "ofac": false
     * }
     */
    DomainInfoResponse: {
      /**
       * Bad
       * @description Whether the domain is flagged as malicious
       */
      bad?: string | null
      geolocation?: components['schemas']['GeolocationResponse'] | null
      /**
       * Ofac
       * @description Whether the domain appears on the OFAC sanctions list
       */
      ofac?: boolean | null
    }
    /**
     * DomainsResponse
     * @example {
     *   "payatu.com": {
     *     "bad": "no",
     *     "geolocation": {
     *       "city": "San Francisco",
     *       "country_long": "United States of America",
     *       "country_short": "US",
     *       "ip": "172.67.72.183",
     *       "latitude": "37.775700",
     *       "longitude": "-122.395203",
     *       "region": "California"
     *     },
     *     "ofac": false
     *   }
     * }
     */
    DomainsResponse: {
      [key: string]: components['schemas']['DomainInfoResponse']
    } | null
    /**
     * DomainsSectionResponse
     * @example {
     *   "domains": {
     *     "computed_with": [
     *       "mobsf"
     *     ],
     *     "data": {
     *       "payatu.com": {
     *         "bad": "no",
     *         "geolocation": {
     *           "city": "San Francisco",
     *           "country_long": "United States of America",
     *           "country_short": "US",
     *           "ip": "172.67.72.183",
     *           "latitude": "37.775700",
     *           "longitude": "-122.395203",
     *           "region": "California"
     *         },
     *         "ofac": false
     *       }
     *     }
     *   }
     * }
     */
    DomainsSectionResponse: {
      domains?: components['schemas']['Envelope_DomainsResponse_'] | null
    }
    /** Envelope[APKDetailsResponse] */
    Envelope_APKDetailsResponse_: {
      /**
       * Computed With
       * @description Tool(s) used to compute this data
       */
      computed_with?: string[] | null
      /** @description The computed result */
      data?: components['schemas']['APKDetailsResponse'] | null
    }
    /** Envelope[AVDetectionsResponse] */
    Envelope_AVDetectionsResponse_: {
      /**
       * Computed With
       * @description Tool(s) used to compute this data
       */
      computed_with?: string[] | null
      /** @description The computed result */
      data?: components['schemas']['AVDetectionsResponse'] | null
    }
    /** Envelope[ActivitiesResponse] */
    Envelope_ActivitiesResponse_: {
      /**
       * Computed With
       * @description Tool(s) used to compute this data
       */
      computed_with?: string[] | null
      /** @description The computed result */
      data?: components['schemas']['ActivitiesResponse'] | null
    }
    /** Envelope[CertificateResponse] */
    Envelope_CertificateResponse_: {
      /**
       * Computed With
       * @description Tool(s) used to compute this data
       */
      computed_with?: string[] | null
      /** @description The computed result */
      data?: components['schemas']['CertificateResponse'] | null
    }
    /** Envelope[ChecksumResponse] */
    Envelope_ChecksumResponse_: {
      /**
       * Computed With
       * @description Tool(s) used to compute this data
       */
      computed_with?: string[] | null
      /** @description The computed result */
      data?: components['schemas']['ChecksumResponse'] | null
    }
    /** Envelope[CodeVulnerabilitiesResponse] */
    Envelope_CodeVulnerabilitiesResponse_: {
      /**
       * Computed With
       * @description Tool(s) used to compute this data
       */
      computed_with?: string[] | null
      /** @description The computed result */
      data?: components['schemas']['CodeVulnerabilitiesResponse'] | null
    }
    /** Envelope[DetailedPermissionsResponse] */
    Envelope_DetailedPermissionsResponse_: {
      /**
       * Computed With
       * @description Tool(s) used to compute this data
       */
      computed_with?: string[] | null
      /** @description The computed result */
      data?: components['schemas']['DetailedPermissionsResponse'] | null
    }
    /** Envelope[DomainsResponse] */
    Envelope_DomainsResponse_: {
      /**
       * Computed With
       * @description Tool(s) used to compute this data
       */
      computed_with?: string[] | null
      /** @description The computed result */
      data?: components['schemas']['DomainsResponse'] | null
    }
    /** Envelope[FuzzyHashesResponse] */
    Envelope_FuzzyHashesResponse_: {
      /**
       * Computed With
       * @description Tool(s) used to compute this data
       */
      computed_with?: string[] | null
      /** @description The computed result */
      data?: components['schemas']['FuzzyHashesResponse'] | null
    }
    /** Envelope[IdentifiersResponse] */
    Envelope_IdentifiersResponse_: {
      /**
       * Computed With
       * @description Tool(s) used to compute this data
       */
      computed_with?: string[] | null
      /** @description The computed result */
      data?: components['schemas']['IdentifiersResponse'] | null
    }
    /** Envelope[NiapAnalysisResponse] */
    Envelope_NiapAnalysisResponse_: {
      /**
       * Computed With
       * @description Tool(s) used to compute this data
       */
      computed_with?: string[] | null
      /** @description The computed result */
      data?: components['schemas']['NiapAnalysisResponse'] | null
    }
    /** Envelope[PermissionsResponse] */
    Envelope_PermissionsResponse_: {
      /**
       * Computed With
       * @description Tool(s) used to compute this data
       */
      computed_with?: string[] | null
      /** @description The computed result */
      data?: components['schemas']['PermissionsResponse'] | null
    }
    /** Envelope[ReceiversResponse] */
    Envelope_ReceiversResponse_: {
      /**
       * Computed With
       * @description Tool(s) used to compute this data
       */
      computed_with?: string[] | null
      /** @description The computed result */
      data?: components['schemas']['ReceiversResponse'] | null
    }
    /** Envelope[ServicesResponse] */
    Envelope_ServicesResponse_: {
      /**
       * Computed With
       * @description Tool(s) used to compute this data
       */
      computed_with?: string[] | null
      /** @description The computed result */
      data?: components['schemas']['ServicesResponse'] | null
    }
    /** Envelope[ThirdPartyResponse] */
    Envelope_ThirdPartyResponse_: {
      /**
       * Computed With
       * @description Tool(s) used to compute this data
       */
      computed_with?: string[] | null
      /** @description The computed result */
      data?: components['schemas']['ThirdPartyResponse'] | null
    }
    /** Envelope[TimelineResponse] */
    Envelope_TimelineResponse_: {
      /**
       * Computed With
       * @description Tool(s) used to compute this data
       */
      computed_with?: string[] | null
      /** @description The computed result */
      data?: components['schemas']['TimelineResponse'] | null
    }
    /** Envelope[Union[list[ManifestResponse], dict]] */
    Envelope_Union_list_ManifestResponse___dict__: {
      /**
       * Computed With
       * @description Tool(s) used to compute this data
       */
      computed_with?: string[] | null
      /**
       * Data
       * @description The computed result
       */
      data?:
        | components['schemas']['ManifestResponse'][]
        | {
            [key: string]: unknown
          }
        | null
    }
    /** Envelope[UrlsResponse] */
    Envelope_UrlsResponse_: {
      /**
       * Computed With
       * @description Tool(s) used to compute this data
       */
      computed_with?: string[] | null
      /** @description The computed result */
      data?: components['schemas']['UrlsResponse'] | null
    }
    /** Envelope[VerdictResponse] */
    Envelope_VerdictResponse_: {
      /**
       * Computed With
       * @description Tool(s) used to compute this data
       */
      computed_with?: string[] | null
      /** @description The computed result */
      data?: components['schemas']['VerdictResponse'] | null
    }
    /** Envelope[YaraMatchesResponse] */
    Envelope_YaraMatchesResponse_: {
      /**
       * Computed With
       * @description Tool(s) used to compute this data
       */
      computed_with?: string[] | null
      /** @description The computed result */
      data?: components['schemas']['YaraMatchesResponse'] | null
    }
    /** Envelope[list[ThreatResponse]] */
    Envelope_list_ThreatResponse__: {
      /**
       * Computed With
       * @description Tool(s) used to compute this data
       */
      computed_with?: string[] | null
      /**
       * Data
       * @description The computed result
       */
      data?: components['schemas']['ThreatResponse'][] | null
    }
    /**
     * FingerprintsResponse
     * @example {
     *   "checksums": {
     *     "computed_with": [
     *       "mobsf"
     *     ],
     *     "data": {
     *       "md5": "f5936822b4567731e11bd3b03ad2305b",
     *       "sha1": "c705b93bce7efeedb5036d7416a056a7a01e6bea",
     *       "sha256": "39ac2d9fe73cb2b4d16ae34bb27dce263c338f1c4e443213302bc3493e9de7eb",
     *       "size": "55.67MB"
     *     }
     *   },
     *   "fuzzy_hashes": {
     *     "computed_with": [
     *       "ssdeep"
     *     ],
     *     "data": {
     *       "ssdeep": [
     *         {
     *           "filename": "classes3.dex",
     *           "fuzzy_hash": "3072:NSOl/RUN4vpCP6MHF10ZFvTXwxbno966V++cGUMFTQT6nMWCPglv9QMj:8GRUOe1UFI+3jODoFD"
     *         }
     *       ]
     *     }
     *   },
     *   "identifiers": {
     *     "computed_with": [
     *       "apkid"
     *     ],
     *     "data": {
     *       "apkid": {
     *         "files": "{}"
     *       }
     *     }
     *   }
     * }
     */
    FingerprintsResponse: {
      checksums?: components['schemas']['Envelope_ChecksumResponse_'] | null
      identifiers?: components['schemas']['Envelope_IdentifiersResponse_'] | null
      fuzzy_hashes?: components['schemas']['Envelope_FuzzyHashesResponse_'] | null
    }
    /**
     * FrostingResponse
     * @example {
     *   "is_frosted": "N/A",
     *   "v2_signature_blocks": []
     * }
     */
    FrostingResponse: {
      /**
       * Is Frosted
       * @description Is the APK frosted
       */
      is_frosted?: boolean | string | null
      /**
       * V2 Signature Blocks
       * @description Signature blocks in the APK
       */
      v2_signature_blocks?: unknown[] | null
    }
    /**
     * FuzzyHashesResponse
     * @example {
     *   "ssdeep": [
     *     {
     *       "filename": "classes3.dex",
     *       "fuzzy_hash": "3072:NSOl/RUN4vpCP6MHF10ZFvTXwxbno966V++cGUMFTQT6nMWCPglv9QMj:8GRUOe1UFI+3jODoFD"
     *     }
     *   ]
     * }
     */
    FuzzyHashesResponse: {
      /**
       * Ssdeep
       * @description SSDeep Fuzzy Hashes
       */
      ssdeep?: components['schemas']['SSDeepHashesResponse'][] | null
    }
    /**
     * FuzzyHashesSectionResponse
     * @example {
     *   "fuzzy-hashes": {
     *     "computed_with": [
     *       "ssdeep"
     *     ],
     *     "data": {
     *       "ssdeep": [
     *         {
     *           "filename": "classes3.dex",
     *           "fuzzy_hash": "3072:NSOl/RUN4vpCP6MHF10ZFvTXwxbno966V++cGUMFTQT6nMWCPglv9QMj:8GRUOe1UFI+3jODoFD"
     *         }
     *       ]
     *     }
     *   }
     * }
     */
    FuzzyHashesSectionResponse: {
      'fuzzy-hashes'?: components['schemas']['Envelope_FuzzyHashesResponse_'] | null
    }
    /**
     * GeolocationResponse
     * @example {
     *   "city": "San Francisco",
     *   "country_long": "United States of America",
     *   "country_short": "US",
     *   "ip": "172.67.72.183",
     *   "latitude": "37.775700",
     *   "longitude": "-122.395203",
     *   "region": "California"
     * }
     */
    GeolocationResponse: {
      /** Ip */
      ip?: string | null
      /** Country Short */
      country_short?: string | null
      /** Country Long */
      country_long?: string | null
      /** Region */
      region?: string | null
      /** City */
      city?: string | null
      /** Latitude */
      latitude?: string | null
      /** Longitude */
      longitude?: string | null
    }
    /** HTTPValidationError */
    HTTPValidationError: {
      /** Detail */
      detail?: components['schemas']['ValidationError'][]
    }
    /**
     * IdentifiersApkidResponse
     * @example {
     *   "files": {
     *     "apkid_version": "3.6.6",
     *     "files": [
     *       {
     *         "filename": "classes.dex",
     *         "matches": {
     *           "compiler": [
     *             "r8"
     *           ]
     *         }
     *       }
     *     ],
     *     "rules_sha256": "e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855"
     *   }
     * }
     */
    IdentifiersApkidResponse: {
      /**
       * Files
       * @description Raw APKiD tool output
       */
      files?:
        | components['schemas']['APKiDResponse']
        | string
        | {
            [key: string]: unknown
          }
        | null
    }
    /**
     * IdentifiersResponse
     * @example {
     *   "apkid": {
     *     "files": {
     *       "apkid_version": "3.6.6",
     *       "files": [
     *         {
     *           "filename": "classes.dex",
     *           "matches": {
     *             "compiler": [
     *               "r8"
     *             ]
     *           }
     *         }
     *       ],
     *       "rules_sha256": "e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855"
     *     }
     *   }
     * }
     */
    IdentifiersResponse: {
      /** @description Results from APKiD */
      apkid?: components['schemas']['IdentifiersApkidResponse'] | null
    }
    /**
     * IdentifiersSectionResponse
     * @example {
     *   "identifiers": {
     *     "computed_with": [
     *       "apkid"
     *     ],
     *     "data": {
     *       "apkid": {
     *         "files": {
     *           "apkid_version": "3.6.6",
     *           "files": [
     *             {
     *               "filename": "classes.dex",
     *               "matches": {
     *                 "compiler": [
     *                   "r8"
     *                 ]
     *               }
     *             }
     *           ],
     *           "rules_sha256": "e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855"
     *         }
     *       }
     *     }
     *   }
     * }
     */
    IdentifiersSectionResponse: {
      identifiers?: components['schemas']['Envelope_IdentifiersResponse_'] | null
    }
    /**
     * ManifestResponse
     * @example {
     *   "component": [
     *     "5.0-5.0.2",
     *     "21"
     *   ],
     *   "description": "This application can be installed on an older version of android that has multiple unfixed vulnerabilities",
     *   "name": "vulnerable_os_version",
     *   "rule": "vulnerable_os_version",
     *   "severity": "high",
     *   "title": "App can be installed on a vulnerable unpatched Android version 5.0-5.0.2, [minSdk=21"
     * }
     */
    ManifestResponse: {
      /**
       * Rule
       * @description Manifest name
       */
      rule?: string | null
      /**
       * Title
       * @description Manifest title
       */
      title?: string | null
      /**
       * Severity
       * @description Manifest threat severity
       */
      severity?: string | null
      /**
       * Description
       * @description Manifest description
       */
      description?: string | null
      /**
       * Name
       * @description Manifest name
       */
      name?: string | null
      /**
       * Component
       * @description Manifest components
       */
      component?: string[] | null
    }
    /**
     * ManifestSectionResponse
     * @example {
     *   "manifest_analysis": {
     *     "computed_with": [
     *       "mobsf"
     *     ],
     *     "data": [
     *       {
     *         "component": [
     *           "5.0-5.0.2",
     *           "21"
     *         ],
     *         "description": "This application can be installed on an older version of android that has multiple unfixed vulnerabilities",
     *         "name": "vulnerable_os_version",
     *         "rule": "vulnerable_os_version",
     *         "severity": "high",
     *         "title": "App can be installed on a vulnerable unpatched Android version 5.0-5.0.2, [minSdk=21"
     *       }
     *     ]
     *   }
     * }
     */
    ManifestSectionResponse: {
      manifest_analysis?:
        components['schemas']['Envelope_Union_list_ManifestResponse___dict__'] | null
    }
    /**
     * NetworkAnalysisResponse
     * @example {
     *   "domains": {
     *     "computed_with": [
     *       "mobsf"
     *     ],
     *     "data": {
     *       "payatu.com": {
     *         "bad": "no",
     *         "geolocation": {
     *           "city": "San Francisco",
     *           "country_long": "United States of America",
     *           "country_short": "US",
     *           "ip": "172.67.72.183",
     *           "latitude": "37.775700",
     *           "longitude": "-122.395203",
     *           "region": "California"
     *         },
     *         "ofac": false
     *       }
     *     }
     *   },
     *   "urls": {
     *     "computed_with": [
     *       "mobsf"
     *     ],
     *     "data": [
     *       {
     *         "path": "jakhar/aseem/diva/APICreds2Activity.java",
     *         "urls": [
     *           "http://payatu.com"
     *         ]
     *       }
     *     ]
     *   }
     * }
     */
    NetworkAnalysisResponse: {
      domains?: components['schemas']['Envelope_DomainsResponse_'] | null
      urls?: components['schemas']['Envelope_UrlsResponse_'] | null
    }
    /**
     * NiapAnalysisResponse
     * @example {}
     */
    NiapAnalysisResponse: {
      [key: string]: unknown
    } | null
    /**
     * NiapSectionResponse
     * @example {
     *   "niap_analysis": {
     *     "computed_with": [
     *       "mobsf"
     *     ],
     *     "data": {}
     *   }
     * }
     */
    NiapSectionResponse: {
      niap_analysis?: components['schemas']['Envelope_NiapAnalysisResponse_'] | null
    }
    /**
     * PermissionInfo
     * @example {
     *   "description": "Allows an application to show system-alert windows. Malicious applications can take over the entire screen of the phone.",
     *   "info": "display system-level alerts",
     *   "status": "dangerous"
     * }
     */
    PermissionInfo: {
      /**
       * Status
       * @description MobSF risk classification for the permission
       */
      status?: string | null
      /**
       * Info
       * @description Short label for what the permission grants
       */
      info?: string | null
      /**
       * Description
       * @description Full description of what the permission allows
       */
      description?: string | null
    }
    /**
     * PermissionsResponse
     * @example {
     *   "android.permission.SYSTEM_ALERT_WINDOW": {
     *     "description": "Allows an application to show system-alert windows. Malicious applications can take over the entire screen of the phone.",
     *     "info": "display system-level alerts",
     *     "status": "dangerous"
     *   }
     * }
     */
    PermissionsResponse: {
      [key: string]: components['schemas']['PermissionInfo']
    } | null
    /**
     * PermissionsSectionResponse
     * @example {
     *   "permissions": {
     *     "computed_with": [
     *       "mobsf"
     *     ],
     *     "data": {
     *       "android.permission.SYSTEM_ALERT_WINDOW": {
     *         "description": "Allows an application to show system-alert windows. Malicious applications can take over the entire screen of the phone.",
     *         "info": "display system-level alerts",
     *         "status": "dangerous"
     *       }
     *     }
     *   }
     * }
     */
    PermissionsSectionResponse: {
      permissions?: components['schemas']['Envelope_PermissionsResponse_'] | null
    }
    /**
     * ReceiversResponse
     * @example [
     *   "com.google.android.commonlib.service.EnqueueService",
     *   "com.google.platform.oaidkit.OAIDLoadService"
     * ]
     */
    ReceiversResponse: string[] | null
    /**
     * ReceiversSectionResponse
     * @example {
     *   "receivers": {
     *     "computed_with": [
     *       "mobsf"
     *     ],
     *     "data": [
     *       "com.google.android.commonlib.service.EnqueueService",
     *       "com.google.platform.oaidkit.OAIDLoadService"
     *     ]
     *   }
     * }
     */
    ReceiversSectionResponse: {
      receivers?: components['schemas']['Envelope_ReceiversResponse_'] | null
    }
    /**
     * ReportResponse
     * @example {
     *   "apk_analysis": {
     *     "acitivities": {
     *       "computed_with": [
     *         "mobsf"
     *       ],
     *       "data": {
     *         "all_activities": [
     *           "com.google.android",
     *           "com.chrome.android"
     *         ],
     *         "main_activity": "com.google.android"
     *       }
     *     },
     *     "apk_details": {
     *       "computed_with": [
     *         "mobsf",
     *         "apk_info"
     *       ],
     *       "data": {
     *         "app_name": "Google",
     *         "frosting": {
     *           "is_frosted": "N/A",
     *           "v2_signature_blocks": []
     *         },
     *         "package": "com.google.android",
     *         "sdk": "21 - None",
     *         "signature": "",
     *         "uaid": "58ef88f27b2b2c48519f804a4ff445e387cee78b",
     *         "version_code": 400000039,
     *         "version_name": "4.2.0"
     *       }
     *     },
     *     "certificate_details": {
     *       "computed_with": [
     *         "apk_info"
     *       ],
     *       "data": {
     *         "issuer": "Common Name: XX：XX, Organizational Unit: XXXX, Organization: XXXX, Locality: XX, State/Province: XX, Country: XXX",
     *         "md5": "9ddde935852443ac9ecc5e794f9917f0",
     *         "not_after": "3021-11-25T09:05:22+00:00",
     *         "not_before": "2023-07-25T09:05:22+00:00",
     *         "sha1": "a6ee6410327ed17751a3e4e7b7a03337d5c00611",
     *         "sha256": "b751f0afed43e56cab08e886d8b65a7a4da654d568e5313cfd056ec6a5b1e028"
     *       }
     *     },
     *     "manifest_analysis": {
     *       "computed_with": [
     *         "mobsf"
     *       ],
     *       "data": [
     *         {
     *           "component": [
     *             "5.0-5.0.2",
     *             "21"
     *           ],
     *           "description": "This application can be installed on an older version of android that has multiple unfixed vulnerabilities",
     *           "name": "vulnerable_os_version",
     *           "rule": "vulnerable_os_version",
     *           "severity": "high",
     *           "title": "App can be installed on a vulnerable unpatched Android version 5.0-5.0.2, [minSdk=21"
     *         }
     *       ]
     *     },
     *     "receivers": {
     *       "computed_with": [
     *         "mobsf"
     *       ],
     *       "data": [
     *         "com.google.android.commonlib.service.EnqueueService",
     *         "com.google.platform.oaidkit.OAIDLoadService"
     *       ]
     *     },
     *     "services": {
     *       "computed_with": [
     *         "mobsf"
     *       ],
     *       "data": [
     *         "com.google.android.share.douyin.StayInDouyinReceiver",
     *         "com.google.myssdk.share.callback.MysShareCallbackReceiver"
     *       ]
     *     }
     *   },
     *   "behavior_analysis": {
     *     "detailed_permissions": {
     *       "computed_with": [
     *         "mobsf"
     *       ],
     *       "data": {
     *         "api_local_file_io": {
     *           "files": {
     *             "jakhar/aseem/diva/MainActivity.java": "40,45,50"
     *           },
     *           "metadata": {
     *             "description": "Local File I/O Operations",
     *             "severity": "info"
     *           }
     *         }
     *       }
     *     },
     *     "permissions": {
     *       "computed_with": [
     *         "mobsf"
     *       ],
     *       "data": {
     *         "android.permission.SYSTEM_ALERT_WINDOW": {
     *           "description": "Allows an application to show system-alert windows. Malicious applications can take over the entire screen of the phone.",
     *           "info": "display system-level alerts",
     *           "status": "dangerous"
     *         }
     *       }
     *     },
     *     "threats": {
     *       "computed_with": [
     *         "quark_engine"
     *       ],
     *       "data": [
     *         {
     *           "confidence": "80%",
     *           "crime": "Read Sensitive Data"
     *         }
     *       ]
     *     }
     *   },
     *   "code_analysis": {
     *     "code_vulnerabilties": {
     *       "computed_with": [
     *         "mobsf"
     *       ],
     *       "data": {
     *         "android_logging": {
     *           "files": {
     *             "jakhar/aseem/diva/LogActivity.java": "24"
     *           },
     *           "metadata": {
     *             "cvss": 7.5,
     *             "cwe": "CWE-532: Insertion of Sensitive Information into Log File",
     *             "description": "The App logs information. Sensitive information should never be logged.",
     *             "masvs": "MSTG-STORAGE-3",
     *             "owasp-mobile": "M2: Insecure Data Storage",
     *             "ref": "https://github.com/MobSF/owasp-mstg/blob/master/Document/0x05d-Testing-Data-Storage.md#logs",
     *             "severity": "warning"
     *           }
     *         }
     *       }
     *     },
     *     "niap_analysis": {
     *       "computed_with": [
     *         "mobsf"
     *       ],
     *       "data": {}
     *     }
     *   },
     *   "fingerprints": {
     *     "checksums": {
     *       "computed_with": [
     *         "mobsf"
     *       ],
     *       "data": {
     *         "md5": "f5936822b4567731e11bd3b03ad2305b",
     *         "sha1": "c705b93bce7efeedb5036d7416a056a7a01e6bea",
     *         "sha256": "39ac2d9fe73cb2b4d16ae34bb27dce263c338f1c4e443213302bc3493e9de7eb",
     *         "size": "55.67MB"
     *       }
     *     },
     *     "fuzzy_hashes": {
     *       "computed_with": [
     *         "ssdeep"
     *       ],
     *       "data": {
     *         "ssdeep": [
     *           {
     *             "filename": "classes3.dex",
     *             "fuzzy_hash": "3072:NSOl/RUN4vpCP6MHF10ZFvTXwxbno966V++cGUMFTQT6nMWCPglv9QMj:8GRUOe1UFI+3jODoFD"
     *           }
     *         ]
     *       }
     *     },
     *     "identifiers": {
     *       "computed_with": [
     *         "apkid"
     *       ],
     *       "data": {
     *         "apkid": {
     *           "files": "{}"
     *         }
     *       }
     *     }
     *   },
     *   "network_analysis": {
     *     "domains": {
     *       "computed_with": [
     *         "mobsf"
     *       ],
     *       "data": {
     *         "payatu.com": {
     *           "bad": "no",
     *           "geolocation": {
     *             "city": "San Francisco",
     *             "country_long": "United States of America",
     *             "country_short": "US",
     *             "ip": "172.67.72.183",
     *             "latitude": "37.775700",
     *             "longitude": "-122.395203",
     *             "region": "California"
     *           },
     *           "ofac": false
     *         }
     *       }
     *     },
     *     "urls": {
     *       "computed_with": [
     *         "mobsf"
     *       ],
     *       "data": [
     *         {
     *           "path": "jakhar/aseem/diva/APICreds2Activity.java",
     *           "urls": [
     *             "http://payatu.com"
     *           ]
     *         }
     *       ]
     *     }
     *   },
     *   "threat_intelligence": {
     *     "av-detections": {
     *       "computed_with": [
     *         "virustotal"
     *       ],
     *       "data": [
     *         {
     *           "Avast": 12
     *         }
     *       ]
     *     },
     *     "sample_timeline": {
     *       "computed_with": [
     *         "fukhara",
     *         "virustotal"
     *       ],
     *       "data": {
     *         "certificate_valid_not_after": "2125-11-01 15:53:29",
     *         "certificate_valid_not_before": "2025-11-25 15:53:29",
     *         "first_submission_on_vt": "2025-11-26 23:20:05",
     *         "last_submission_on_vt": "2026-06-23 01:07:16",
     *         "latest_file_found_in_apk": "2025-11-27 04:04:48",
     *         "oldest_file_found_in_apk": "2025-11-27 04:04:42",
     *         "upload_on_fukhara": "2026-07-08 11:58:31.763690"
     *       }
     *     },
     *     "third-party-apps": {
     *       "computed_with": [
     *         "virustotal",
     *         "malwarebazaar"
     *       ],
     *       "data": {
     *         "malwarebazaar": "https://bazaar.abuse.ch/sample/<sha256>",
     *         "virustotal": "https://www.virustotal.com/api/v3/files/<sha256>"
     *       }
     *     },
     *     "yara_matches": {
     *       "computed_with": [
     *         "yara_analyzer"
     *       ],
     *       "data": {
     *         "matches": [
     *           {
     *             "rules": [
     *               "Android_Dynamic_Code_Loading",
     *               "Android_Root_Detection_Bypass"
     *             ],
     *             "source": "classes.dex"
     *           }
     *         ]
     *       }
     *     }
     *   }
     * }
     */
    ReportResponse: {
      fingerprints?: components['schemas']['FingerprintsResponse'] | null
      threat_intelligence?: components['schemas']['ThreatIntelligenceResponse'] | null
      apk_analysis?: components['schemas']['AppAnalysisResponse'] | null
      code_analysis?: components['schemas']['CodeAnalysisResponse'] | null
      behavior_analysis?: components['schemas']['BehaviorAnalysisResponse'] | null
      network_analysis?: components['schemas']['NetworkAnalysisResponse'] | null
    }
    /**
     * SSDeepHashesResponse
     * @example {
     *   "filename": "classes3.dex",
     *   "fuzzy_hash": "3072:NSOl/RUN4vpCP6MHF10ZFvTXwxbno966V++cGUMFTQT6nMWCPglv9QMj:8GRUOe1UFI+3jODoFD"
     * }
     */
    SSDeepHashesResponse: {
      /**
       * Filename
       * @description Filename of the hashed file
       */
      filename?: string | null
      /**
       * Fuzzy Hash
       * @description Fuzzy hash of the file
       */
      fuzzy_hash?: string | null
    }
    /**
     * ServicesResponse
     * @example [
     *   "com.google.android.share.douyin.StayInDouyinReceiver",
     *   "com.google.myssdk.share.callback.MysShareCallbackReceiver"
     * ]
     */
    ServicesResponse: string[] | null
    /**
     * ServicesSectionResponse
     * @example {
     *   "services": {
     *     "computed_with": [
     *       "mobsf"
     *     ],
     *     "data": [
     *       "com.google.android.share.douyin.StayInDouyinReceiver",
     *       "com.google.myssdk.share.callback.MysShareCallbackReceiver"
     *     ]
     *   }
     * }
     */
    ServicesSectionResponse: {
      services?: components['schemas']['Envelope_ServicesResponse_'] | null
    }
    /**
     * ThirdPartyResponse
     * @example {
     *   "malwarebazaar": "https://bazaar.abuse.ch/sample/<sha256>",
     *   "virustotal": "https://www.virustotal.com/api/v3/files/<sha256>"
     * }
     */
    ThirdPartyResponse: {
      /**
       * Virustotal
       * @description Link to the VirusTotal analysis report
       */
      virustotal?: string | null
      /**
       * Malwarebazaar
       * @description Link to the MalwareBazaar sample page
       */
      malwarebazaar?: string | null
    }
    /**
     * ThirdPartySectionResponse
     * @example {
     *   "third-party-apps": {
     *     "computed_with": [
     *       "virustotal",
     *       "malwarebazaar"
     *     ],
     *     "data": {
     *       "malwarebazaar": "https://bazaar.abuse.ch/sample/<sha256>",
     *       "virustotal": "https://www.virustotal.com/api/v3/files/<sha256>"
     *     }
     *   }
     * }
     */
    ThirdPartySectionResponse: {
      'third-party-apps'?: components['schemas']['Envelope_ThirdPartyResponse_'] | null
    }
    /**
     * ThreatIntelligenceResponse
     * @example {
     *   "av-detections": {
     *     "computed_with": [
     *       "virustotal"
     *     ],
     *     "data": [
     *       {
     *         "Avast": 12
     *       }
     *     ]
     *   },
     *   "sample_timeline": {
     *     "computed_with": [
     *       "fukhara",
     *       "virustotal"
     *     ],
     *     "data": {
     *       "certificate_valid_not_after": "2125-11-01 15:53:29",
     *       "certificate_valid_not_before": "2025-11-25 15:53:29",
     *       "first_submission_on_vt": "2025-11-26 23:20:05",
     *       "last_submission_on_vt": "2026-06-23 01:07:16",
     *       "latest_file_found_in_apk": "2025-11-27 04:04:48",
     *       "oldest_file_found_in_apk": "2025-11-27 04:04:42",
     *       "upload_on_fukhara": "2026-07-08 11:58:31.763690"
     *     }
     *   },
     *   "third-party-apps": {
     *     "computed_with": [
     *       "virustotal",
     *       "malwarebazaar"
     *     ],
     *     "data": {
     *       "malwarebazaar": "https://bazaar.abuse.ch/sample/<sha256>",
     *       "virustotal": "https://www.virustotal.com/api/v3/files/<sha256>"
     *     }
     *   },
     *   "yara_matches": {
     *     "computed_with": [
     *       "yara_analyzer"
     *     ],
     *     "data": {
     *       "matches": [
     *         {
     *           "rules": [
     *             "Android_Dynamic_Code_Loading",
     *             "Android_Root_Detection_Bypass"
     *           ],
     *           "source": "classes.dex"
     *         }
     *       ]
     *     }
     *   }
     * }
     */
    ThreatIntelligenceResponse: {
      sample_timeline?: components['schemas']['Envelope_TimelineResponse_'] | null
      yara_matches?: components['schemas']['Envelope_YaraMatchesResponse_'] | null
      'av-detections'?: components['schemas']['Envelope_AVDetectionsResponse_'] | null
      'third-party-apps'?: components['schemas']['Envelope_ThirdPartyResponse_'] | null
    }
    /**
     * ThreatResponse
     * @example {
     *   "confidence": "80%",
     *   "crime": "Read Sensitive Data"
     * }
     */
    ThreatResponse: {
      /**
       * Crime
       * @description Detected behavioral crime/capability
       */
      crime?: string | null
      /**
       * Confidence
       * @description Confidence level of the detection
       */
      confidence?: string | null
    }
    /**
     * ThreatsSectionResponse
     * @example {
     *   "threats": {
     *     "computed_with": [
     *       "quark_engine"
     *     ],
     *     "data": [
     *       {
     *         "confidence": "80%",
     *         "crime": "Read Sensitive Data"
     *       }
     *     ]
     *   }
     * }
     */
    ThreatsSectionResponse: {
      threats?: components['schemas']['Envelope_list_ThreatResponse__'] | null
    }
    /**
     * TimelineResponse
     * @example {
     *   "certificate_valid_not_after": "2125-11-01 15:53:29",
     *   "certificate_valid_not_before": "2025-11-25 15:53:29",
     *   "first_submission_on_vt": "2025-11-26 23:20:05",
     *   "last_submission_on_vt": "2026-06-23 01:07:16",
     *   "latest_file_found_in_apk": "2025-11-27 04:04:48",
     *   "oldest_file_found_in_apk": "2025-11-27 04:04:42",
     *   "upload_on_fukhara": "2026-07-08 11:58:31.763690"
     * }
     */
    TimelineResponse: {
      /**
       * Oldest File Found In Apk
       * @description Datetime of the oldest file found inside the APK sample
       */
      oldest_file_found_in_apk?: string | null
      /**
       * Certificate Valid Not Before
       * @description Datetime of the certificate creation
       */
      certificate_valid_not_before?: string | null
      /**
       * Latest File Found In Apk
       * @description Datetime of the latest file found inside the APK sample
       */
      latest_file_found_in_apk?: string | null
      /**
       * First Submission On Vt
       * @description Datetime of the first submission on VirusTotal
       */
      first_submission_on_vt?: string | null
      /**
       * Last Submission On Vt
       * @description Datetime of the latest submission on VirusTotal
       */
      last_submission_on_vt?: string | null
      /**
       * Upload On Fukhara
       * @description Datetime of submission on Fukhara
       */
      upload_on_fukhara?: string | null
      /**
       * Certificate Valid Not After
       * @description Datetime of the certificate expiration
       */
      certificate_valid_not_after?: string | null
    }
    /**
     * TimelineSectionResponse
     * @example {
     *   "sample_timeline": {
     *     "computed_with": [
     *       "fukhara",
     *       "virustotal"
     *     ],
     *     "data": {
     *       "certificate_valid_not_after": "2125-11-01 15:53:29",
     *       "certificate_valid_not_before": "2025-11-25 15:53:29",
     *       "first_submission_on_vt": "2025-11-26 23:20:05",
     *       "last_submission_on_vt": "2026-06-23 01:07:16",
     *       "latest_file_found_in_apk": "2025-11-27 04:04:48",
     *       "oldest_file_found_in_apk": "2025-11-27 04:04:42",
     *       "upload_on_fukhara": "2026-07-08 11:58:31.763690"
     *     }
     *   }
     * }
     */
    TimelineSectionResponse: {
      sample_timeline?: components['schemas']['Envelope_TimelineResponse_'] | null
    }
    /**
     * UrlEntryResponse
     * @example {
     *   "path": "jakhar/aseem/diva/APICreds2Activity.java",
     *   "urls": [
     *     "http://payatu.com"
     *   ]
     * }
     */
    UrlEntryResponse: {
      /**
       * Urls
       * @description URL(s) found at this location
       */
      urls?: string[] | null
      /**
       * Path
       * @description Source file where the URL(s) were found
       */
      path?: string | null
    }
    /**
     * UrlsResponse
     * @example [
     *   {
     *     "path": "jakhar/aseem/diva/APICreds2Activity.java",
     *     "urls": [
     *       "http://payatu.com"
     *     ]
     *   }
     * ]
     */
    UrlsResponse: components['schemas']['UrlEntryResponse'][] | null
    /**
     * UrlsSectionResponse
     * @example {
     *   "urls": {
     *     "computed_with": [
     *       "mobsf"
     *     ],
     *     "data": [
     *       {
     *         "path": "jakhar/aseem/diva/APICreds2Activity.java",
     *         "urls": [
     *           "http://payatu.com"
     *         ]
     *       }
     *     ]
     *   }
     * }
     */
    UrlsSectionResponse: {
      urls?: components['schemas']['Envelope_UrlsResponse_'] | null
    }
    /** ValidationError */
    ValidationError: {
      /** Location */
      loc: (string | number)[]
      /** Message */
      msg: string
      /** Error Type */
      type: string
      /** Input */
      input?: unknown
      /** Context */
      ctx?: Record<string, never>
    }
    /**
     * VerdictResponse
     * @example {
     *   "reason": "Continuous communication has been found between the sample and suspecious domains",
     *   "response": "Delete the sample immediately and hand the phone over to a forensics team for deep analysis",
     *   "severity": "Medium",
     *   "verdict": "Malicious"
     * }
     */
    VerdictResponse: {
      /**
       * Verdict
       * @description Final verdict of whether the sample is malicious or not?
       */
      verdict?: string | null
      /**
       * Severity
       * @description How malicious is this sample?
       */
      severity?: string | null
      /**
       * Reason
       * @description Why has this sample been categorized as such?
       */
      reason?: string | null
      /**
       * Response
       * @description What should the user do to respond to this sample?
       */
      response?: string | null
    }
    /**
     * VerdictSectionResponse
     * @example {
     *   "verdict": {
     *     "computed_with": [
     *       "fukhara"
     *     ],
     *     "data": {
     *       "reason": "Continuous communication has been found between the sample and suspecious domains",
     *       "response": "Delete the sample immediately and hand the phone over to a forensics team for deep analysis",
     *       "severity": "Medium",
     *       "verdict": "Malicious"
     *     }
     *   }
     * }
     */
    VerdictSectionResponse: {
      verdict?: components['schemas']['Envelope_VerdictResponse_'] | null
    }
    /**
     * YaraMatchResponse
     * @example {
     *   "rules": [
     *     "Android_Dynamic_Code_Loading",
     *     "Android_Root_Detection_Bypass"
     *   ],
     *   "source": "classes.dex"
     * }
     */
    YaraMatchResponse: {
      /**
       * Source
       * @description File the YARA rule matched against
       */
      source?: string | null
      /**
       * Rules
       * @description YARA rule name(s) that matched
       */
      rules?: string[] | null
    }
    /**
     * YaraMatchesResponse
     * @example {
     *   "matches": [
     *     {
     *       "rules": [
     *         "Android_Dynamic_Code_Loading",
     *         "Android_Root_Detection_Bypass"
     *       ],
     *       "source": "classes.dex"
     *     }
     *   ]
     * }
     */
    YaraMatchesResponse: {
      /**
       * Matches
       * @description List of YARA rule matches found for the sample
       */
      matches?: components['schemas']['YaraMatchResponse'][] | null
    }
    /**
     * YaraSectionResponse
     * @example {
     *   "yara_matches": {
     *     "computed_with": [
     *       "yara_analyzer"
     *     ],
     *     "data": {
     *       "matches": [
     *         {
     *           "rules": [
     *             "Android_Dynamic_Code_Loading",
     *             "Android_Root_Detection_Bypass"
     *           ],
     *           "source": "classes.dex"
     *         }
     *       ]
     *     }
     *   }
     * }
     */
    YaraSectionResponse: {
      yara_matches?: components['schemas']['Envelope_YaraMatchesResponse_'] | null
    }
  }
  responses: never
  parameters: never
  requestBodies: never
  headers: never
  pathItems: never
}

export type $defs = Record<string, never>

export type external = Record<string, never>

export interface operations {
  /** Home */
  home__get: {
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          'application/json': unknown
        }
      }
    }
  }
  /**
   * Submit an APK for analysis
   * @description Upload an APK file, computes its SHA-256 hash, and queues it for analysis. Return the SHA-256 hash of the APK file
   */
  analyze_apk_api_analyze__post: {
    requestBody: {
      content: {
        'multipart/form-data': components['schemas']['Body_analyze_apk_api_analyze__post']
      }
    }
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          'application/json': components['schemas']['AnalyzeResponse']
        }
      }
      /** @description Validation Error */
      422: {
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  /**
   * List all APK analyses
   * @description Return a list of all APK analysis reports that have been submitted and analyzed
   */
  get_reports_api_reports__get: {
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          'application/json': unknown
        }
      }
    }
  }
  /**
   * Get the full analysis report
   * @description Return the complete, aggregated analysis report (fingerprints, threat intelligence, app information, code analysis, behavior analysis, and network analysis)
   */
  get_report_api_report__id___get: {
    parameters: {
      path: {
        /** @description Analysis report ID (SHA256 checksum of the APK file) */
        id: string
      }
    }
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          'application/json': components['schemas']['ReportResponse']
        }
      }
      /** @description Validation Error */
      422: {
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  /**
   * Get the sample's final verdict
   * @description Return the final verdict(malicious or not, severity, reason, response needed
   */
  get_verdict_api_report__id__verdict__get: {
    parameters: {
      path: {
        /** @description Analysis report ID (SHA256 checksum of the APK file */
        id: string
      }
    }
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          'application/json': components['schemas']['VerdictSectionResponse']
        }
      }
      /** @description Validation Error */
      422: {
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  /**
   * Get fingerprints data
   * @description Return all the fingerprints data (checksums, identifiers, fuzzy hashes)
   */
  get_fingerprints_api_report__id__fingerprints__get: {
    parameters: {
      path: {
        /** @description Analysis report ID (SHA256 checksum of the APK file) */
        id: string
      }
    }
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          'application/json': components['schemas']['FingerprintsResponse']
        }
      }
      /** @description Validation Error */
      422: {
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  /**
   * Get file checksums
   * @description Return file checksums (e.g. MD5, SHA256) computed
   */
  get_checksums_api_report__id__fingerprints_checksums__get: {
    parameters: {
      path: {
        /** @description Analysis report ID (SHA256 checksum of the APK file) */
        id: string
      }
    }
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          'application/json': components['schemas']['ChecksumSectionResponse']
        }
      }
      /** @description Validation Error */
      422: {
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  /**
   * Get APK identifiers
   * @description Return packer/obfuscator/compiler identifiers
   */
  get_identifiers_api_report__id__fingerprints_identifiers__get: {
    parameters: {
      path: {
        /** @description Analysis report ID (SHA256 checksum of the APK file) */
        id: string
      }
    }
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          'application/json': components['schemas']['IdentifiersSectionResponse']
        }
      }
      /** @description Validation Error */
      422: {
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  /**
   * Get fuzzy hashes
   * @description Return fuzzy hash values (e.g. ssdeep) used for similarity comparisons
   */
  get_fuzzy_hashes_api_report__id__fingerprints_fuzzy_hashes__get: {
    parameters: {
      path: {
        /** @description Analysis report ID (SHA256 checksum of the APK file) */
        id: string
      }
    }
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          'application/json': components['schemas']['FuzzyHashesSectionResponse']
        }
      }
      /** @description Validation Error */
      422: {
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  /**
   * Get all threat intelligence data
   * @description Return all the threat intelligence data (sample timeline, YARA matches, antivirus detections, third-party lookups)
   */
  get_threat_intelligence_api_report__id__threat_intelligence__get: {
    parameters: {
      path: {
        /** @description Analysis report ID (SHA256 checksum of the APK file) */
        id: string
      }
    }
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          'application/json': components['schemas']['ThreatIntelligenceResponse']
        }
      }
      /** @description Validation Error */
      422: {
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  /**
   * Get sample timeline
   * @description Return key dates for the sample (file creation, certficate validaity, first/last submission)
   */
  get_sample_timeline_api_report__id__threat_intelligence_timeline__get: {
    parameters: {
      path: {
        /** @description Analysis report ID (SHA256 checksum of the APK file) */
        id: string
      }
    }
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          'application/json': components['schemas']['TimelineSectionResponse']
        }
      }
      /** @description Validation Error */
      422: {
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  /**
   * Get YARA rule matches
   * @description Return the YARA rule match results
   */
  get_yara_analysis_api_report__id__threat_intelligence_yara__get: {
    parameters: {
      path: {
        /** @description Analysis report ID (SHA256 checksum of the APK file) */
        id: string
      }
    }
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          'application/json': components['schemas']['YaraSectionResponse']
        }
      }
      /** @description Validation Error */
      422: {
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  /**
   * Get popular antivirus detections
   * @description Return the popular antivirus engine detections
   */
  get_antivirus_detections_api_report__id__threat_intelligence_popular_av_detections__get: {
    parameters: {
      path: {
        /** @description Analysis report ID (SHA256 checksum of the APK file) */
        id: string
      }
    }
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          'application/json': components['schemas']['AVDetectionsSectionResponse']
        }
      }
      /** @description Validation Error */
      422: {
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  /**
   * Get 3rd-party lookup results
   * @description Return lookup results for 3rd-party threat intelligence sources (e.g. VirusTotal, MalwareBazaar)
   */
  get_third_party_apps_api_report__id__threat_intelligence_third_party_apps__get: {
    parameters: {
      path: {
        /** @description Analysis report ID (SHA256 checksum of the APK file) */
        id: string
      }
    }
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          'application/json': components['schemas']['ThirdPartySectionResponse']
        }
      }
      /** @description Validation Error */
      422: {
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  /**
   * Get all app information
   * @description Return the full app information (details, certificates, manifests, activities, receivers, services)
   */
  get_app_analysis_api_report__id__app__get: {
    parameters: {
      path: {
        /** @description Analysis report ID (SHA256 checksum of the APK file) */
        id: string
      }
    }
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          'application/json': components['schemas']['AppAnalysisResponse']
        }
      }
      /** @description Validation Error */
      422: {
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  /**
   * Get app details
   * @description Return basic app metadata (package name, version, size, etc.
   */
  get_app_details_api_report__id__app_details__get: {
    parameters: {
      path: {
        /** @description Analysis report ID (SHA256 checksum of the APK file) */
        id: string
      }
    }
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          'application/json': components['schemas']['APKDetailsSectionResponse']
        }
      }
      /** @description Validation Error */
      422: {
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  /**
   * Get signing certificate details
   * @description Return the APK's signing certificate details (issuer, subject, validity, etc.)
   */
  get_app_certificate_api_report__id__app_certificate__get: {
    parameters: {
      path: {
        /** @description Analysis report ID (SHA256 checksum of the APK file) */
        id: string
      }
    }
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          'application/json': components['schemas']['CertificateSectionResponse']
        }
      }
      /** @description Validation Error */
      422: {
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  /**
   * Get app manifests
   * @description Return a list of manifests declared in the app's manifest files (AndroidManifest.xml, etc.)
   */
  get_app_manifests_api_report__id__app_manifests__get: {
    parameters: {
      path: {
        /** @description Analysis report ID (SHA256 checksum of the APK file) */
        id: string
      }
    }
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          'application/json': components['schemas']['ManifestSectionResponse']
        }
      }
      /** @description Validation Error */
      422: {
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  /**
   * Get app activities
   * @description Return a list of activities declared in the app's manifest files (AndroidManifest.xml, etc. )
   */
  get_app_activities_api_report__id__app_activities__get: {
    parameters: {
      path: {
        /** @description Analysis report ID (SHA256 checksum of the APK file) */
        id: string
      }
    }
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          'application/json': components['schemas']['ActivitiesSectionResponse']
        }
      }
      /** @description Validation Error */
      422: {
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  /**
   * Get app receivers
   * @description Return a list of receivers declared in the app's manifest files (AndroidManifest.xml, etc.)
   */
  get_app_receivers_api_report__id__app_receivers__get: {
    parameters: {
      path: {
        /** @description Analysis report ID (SHA256 checksum of the APK file) */
        id: string
      }
    }
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          'application/json': components['schemas']['ReceiversSectionResponse']
        }
      }
      /** @description Validation Error */
      422: {
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  /**
   * Get app services
   * @description Return a list of services declared in the app's manifest files (AndroidManifest.xml, etc.)
   */
  get_app_services_api_report__id__app_services__get: {
    parameters: {
      path: {
        /** @description Analysis report ID (SHA256 checksum of the APK file) */
        id: string
      }
    }
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          'application/json': components['schemas']['ServicesSectionResponse']
        }
      }
      /** @description Validation Error */
      422: {
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  /**
   * Get all code analysis results
   * @description Return the full code analysis results (NIAP compliance, vulnerabilities)
   */
  get_code_analysis_api_report__id__code__get: {
    parameters: {
      path: {
        /** @description Analysis report ID (SHA256 checksum of the APK file) */
        id: string
      }
    }
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          'application/json': components['schemas']['CodeAnalysisResponse']
        }
      }
      /** @description Validation Error */
      422: {
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  /**
   * Get NIAP analysis
   * @description Return the NIAP (National Information Assurance Program) compliance analysis results
   */
  get_niap_analysis_api_report__id__code_niap__get: {
    parameters: {
      path: {
        /** @description Analysis report ID (SHA256 checksum of the APK file) */
        id: string
      }
    }
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          'application/json': components['schemas']['NiapSectionResponse']
        }
      }
      /** @description Validation Error */
      422: {
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  /**
   * Get code vulnerabilities
   * @description Return a list of vulnerabilities detected via static analysis of the code
   */
  get_code_vulnerabilities_api_report__id__code_vulnerabilities__get: {
    parameters: {
      path: {
        /** @description Analysis report ID (SHA256 checksum of the APK file) */
        id: string
      }
    }
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          'application/json': components['schemas']['CodeVulnerabilitiesSectionResponse']
        }
      }
      /** @description Validation Error */
      422: {
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  /**
   * Get all behavior analysis results
   * @description Return the full behavior analysis results (threats, permissions, detailed permissions)
   */
  get_behavior_analysis_api_report__id__behavior__get: {
    parameters: {
      path: {
        /** @description Analysis report ID (SHA256 checksum of the APK file) */
        id: string
      }
    }
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          'application/json': components['schemas']['BehaviorAnalysisResponse']
        }
      }
      /** @description Validation Error */
      422: {
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  /**
   * Get behavioral threats
   * @description Return a list of threats (crimes) detected
   */
  get_threats_analysis_api_report__id__behavior_threats__get: {
    parameters: {
      path: {
        /** @description Analysis report ID (SHA256 checksum of the APK file) */
        id: string
      }
    }
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          'application/json': components['schemas']['ThreatsSectionResponse']
        }
      }
      /** @description Validation Error */
      422: {
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  /**
   * Get permissions analysis
   * @description Return a list of permissions requested by the APK
   */
  get_permission_analysis_api_report__id__behavior_permissions__get: {
    parameters: {
      path: {
        /** @description Analysis report ID (SHA256 checksum of the APK file) */
        id: string
      }
    }
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          'application/json': components['schemas']['PermissionsSectionResponse']
        }
      }
      /** @description Validation Error */
      422: {
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  /**
   * Get detailed permission analysis
   * @description Return a list of detailed permissions requested by the APK
   */
  get_detailed_permissions_api_report__id__behavior_detailed_permissions__get: {
    parameters: {
      path: {
        /** @description Analysis report ID (SHA256 checksum of the APK file) */
        id: string
      }
    }
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          'application/json': components['schemas']['DetailedPermissionsSectionResponse']
        }
      }
      /** @description Validation Error */
      422: {
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  /**
   * Get control-flow graph data
   * @description Return the control-flow graph visualization of the behavior of the APK
   */
  get_control_flow_api_report__id__control_flow__get: {
    parameters: {
      path: {
        /** @description Analysis report ID (SHA256 checksum of the APK file) */
        id: string
      }
    }
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          'application/json': unknown
        }
      }
      /** @description Validation Error */
      422: {
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  /**
   * Get all network analysis
   * @description Return the network analysis results (domains and URLs)
   */
  get_network_analysis_api_report__id__network__get: {
    parameters: {
      path: {
        /** @description Analysis report ID (SHA256 checksum of the APK file) */
        id: string
      }
    }
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          'application/json': components['schemas']['NetworkAnalysisResponse']
        }
      }
      /** @description Validation Error */
      422: {
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  /**
   * Get network domains
   * @description Return a list of network domains accessed
   */
  get_domain_analysis_api_report__id__network_domains__get: {
    parameters: {
      path: {
        /** @description Analysis report ID (SHA256 checksum of the APK file) */
        id: string
      }
    }
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          'application/json': components['schemas']['DomainsSectionResponse']
        }
      }
      /** @description Validation Error */
      422: {
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  /**
   * Get network URLs
   * @description Return a list of network URLs accessed
   */
  get_url_analysis_api_report__id__network_urls__get: {
    parameters: {
      path: {
        /** @description Analysis report ID (SHA256 checksum of the APK file) */
        id: string
      }
    }
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          'application/json': components['schemas']['UrlsSectionResponse']
        }
      }
      /** @description Validation Error */
      422: {
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
}
